GET http://localhost:4000/dataBuku

###
POST http://localhost:4000/add-dataBuku
Content-Type: application/json

{
    "id": "a1",
    "kategori": "Mata Kuliah",
    "nama_buku": "Kriptografi",
    "harga": 100000,
    "stok": 5,
    "penerbit": "Ya",
    "tahun": "2020"
}

###
PUT http://localhost:4000/edit-dataBuku/a3
Content-Type: application/json

{
    "id": "a1",
    "kategori": "Mata Kuliah",
    "nama_buku": "Kriptografi",
    "harga": 100000,
    "stok": 5,
    "penerbit": "Siapa",
    "tahun": "2020"
}

###
DELETE http://localhost:4000/delete-dataBuku/a1


###
GET http://localhost:4000/dataPenerbit
###
POST http://localhost:4000/add-dataPenerbit
Content-Type: application/json

{
    "id": "A2",
    "nama": "Hanung",
    "alamat": "Kadipaten",
    "kota": "Yogyakarta",
    "telepon": "0832",
    "email": "h@gmail.com"
}

###
PUT  http://localhost:4000/edit-dataPenerbit/A2
Content-Type: application/json

{
    "id": "A2",
    "nama": "Hanung",
    "alamat": "Kadipaten",
    "kota": "Yogyakarta",
    "telepon": "08321",
    "email": "h@gmail.com"
}

###
DELETE http://localhost:4000/delete-dataPenerbit/A2


###
GET http://localhost:4000/profile/syifanur

###
POST http://localhost:4000/register
Content-Type: application/json

{

    "username": "cobalho",
    "password": "bismillah"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "admin",
    "password": "iniadmin"
}

###
PUT http://localhost:4000/profile/update/admin
Content-Type: application/json

{
    "username": "admin",
    "password": "iniadmin"
}