GET http://localhost:4000/dataBuku

###
POST http://localhost:4000/add-dataBuku
Content-Type: application/json

{
    "id": "a1",
    "kategori": "Mata Kuliah",
    "nama_buku": "Kriptografi",
    "harga": 100000,
    "stok": 5,
    "penerbit": "Ya",
    "tahun": "2020"
}

###
PUT http://localhost:4000/edit-dataBuku/a3
Content-Type: application/json

{
    "id": "a1",
    "kategori": "Mata Kuliah",
    "nama_buku": "Kriptografi",
    "harga": 100000,
    "stok": 5,
    "penerbit": "Siapa",
    "tahun": "2020"
}

###
DELETE http://localhost:4000/delete-dataBuku/a1


###
GET http://localhost:4000/dataPenerbit
###
POST http://localhost:4000/add-dataPenerbit
Content-Type: application/json

{
    "id": "A2",
    "nama": "Hanung",
    "alamat": "Kadipaten",
    "kota": "Yogyakarta",
    "telepon": "0832",
    "email": "h@gmail.com"
}

###
PUT  https://perpus-syifa194naufal207-797713225706.us-central1.run.app/edit-dataPenerbit/P1
Content-Type: application/json

{
    "id": "P1",
        "nama": "Eko Polosoro",
        "alamat": "Jln Nangka",
        "kota": "Bandung",
        "telepon": "08564321765",
        "email": "Ekoploro@gmail.com",
      
}

###
DELETE http://localhost:4000/delete-dataPenerbit/A2


###
GET http://localhost:4000/profile/syifanur

###
POST https://perpus-syifa194naufal207-797713225706.us-central1.run.app/register
Content-Type: application/json

{

    "username": "sabrina",
    "password": "123"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "admin",
    "password": "iniadmin"
}

###
PUT http://localhost:4000/profile/update/admin
Content-Type: application/json

{
    "username": "admin",
    "password": "iniadmin"
}